from backend.settings.app_vars import *
from backend.settings.apps import *
from backend.settings.base import *
from backend.settings.database import *
from backend.settings.middleware import *
from backend.settings.password_validators import *
from backend.settings.redis import *
from backend.settings.rest_framework import *
from backend.settings.templates import *
from backend.settings.all_auth import *
