# Generated by Django 4.2 on 2024-10-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailqueue",
            options={"ordering": ["-priority", "-added"]},
        ),
    ]
