# Generated by Django 4.2 on 2024-10-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_management", "0003_alter_emailverification_using_for_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PhoneVerification",
        ),
    ]
