# Generated by Django 4.2 on 2024-10-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_management", "0004_delete_phoneverification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermanage",
            name="user_type",
        ),
    ]
