# Generated by Django 4.2 on 2024-10-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CosmosModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("tax_id", models.IntegerField(blank=True, null=True)),
                ("abundance_score", models.FloatField(blank=True, null=True)),
                (
                    "normalized_reads_frequency",
                    models.FloatField(blank=True, null=True),
                ),
                ("relative_abundance", models.FloatField(blank=True, null=True)),
                ("reads", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
