# Generated by Django 4.2 on 2024-10-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cosmosmodel",
            name="file_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
